### ISSUE TITLE
Add a script to rotate meeting times

### ISSUE THREAD

**Issue by siliconninja** [siliconninja/RHLUG-Website#2]
Adding this issue as a TODO for the future. Anyone can get to it.

Rotate meeting times automatically using a script so we don't have to update the site manually. Picture:
![image](https://user-images.githubusercontent.com/29907828/78831407-968cb000-79b7-11ea-9b09-e3357d615760.png)

Do it on the client side using JavaScript or similar so we won't have to use a backend server. Maybe use information from wiki.rhlug.org (we'll keep the text consistent) so we update the meeting times all in one place. It might be tricky to do that without breaking XSS rules so a backend server might be needed for that solution. In that case pull from a text file or similar on this repo.

There might already be a solution out there so we don't have to reinvent the wheel.

If we have to use a backend server we can do that but it's a last resort.

**Comment by RealJasomo** [comment]
My latest commit fixes this issue

**Comment by siliconninja** [comment]
Wow, thank you for your work on this!
